### ISSUE TITLE
problem with the loading of the models in the collab

### ISSUE THREAD

**Issue by aviv926** [camenduru/whisper-jax-colab#2]
When  I run any of colab notebook I got this error 

`alueError                                Traceback (most recent call last)
[<ipython-input-1-ba8bbd57f420>](https://localhost:8080/#) in <cell line: 11>()
      9 import jax.numpy as jnp
     10 
---> 11 pipeline = FlaxWhisperPipline("openai/whisper-medium", dtype=jnp.float16)
     12 from jax.experimental.compilation_cache import compilation_cache as cc
     13 cc.initialize_cache("/content/jax_cache")

4 frames
[/usr/local/lib/python3.10/dist-packages/transformers/modeling_flax_utils.py](https://localhost:8080/#) in params(self)
    268     def params(self) -> Union[Dict, FrozenDict]:
    269         if not self._is_initialized:
--> 270             raise ValueError(
    271                 "`params` cannot be accessed from model when the model is created with `_do_init=False`. "
    272                 "You must call `init_weights` manually and store the params outside of the model and "

ValueError: `params` cannot be accessed from model when the model is created with `_do_init=False`. You must call `init_weights` manually and store the params outside of the model and pass it explicitly where needed.`

Whats can be the problem?

**Comment by angediablo** [comment]
I am facing the exact same problem since today. It seems like pipleline cannot be instantiate with the model and other parameters such as bloat and batch size.

Is there any workaround ?

No error is raised when pipeline is initiatee without any parameters
`pipeline = FlaxWhisperPipline()`

How can the parameters be assigned afterward ?

**Comment by nftblackmagic** [comment]
Found a WAR. Just decrease the transformers version to 
!pip install transformers==4.31.0

I think the latest transformers version cause the issue.

**Comment by camenduru** [comment]
thanks @nftblackmagic ❤

**Comment by aviv926** [comment]
It seems the problem still exists in a different form
![image](https://github.com/camenduru/whisper-jax-colab/assets/51673860/8d2446f0-5a1a-4529-9f20-9a99959c8a3e)

Thanks for the previous fix!
